### PR TITLE
README Cleanup

### PR DESCRIPTION
**Pull request by bgiesing**
Here's some things you could do to the readme. @NicholasBuse 

- Change OpenGApps to Open GApps and APKMirror to APK Mirror.
- Enable syntax highlighting.
- Add link for where to find the codenames to use with the script
- Combine install into one line
- Add Supported Sites section to make it cleaner and easier to add other sites in future (if necessary)
- Link to APK Mirror

### CODE REVIEW

**Comment by NicholasBuse** [comment]
Thanks!  Have you tried it out yet?

**Comment by bgiesing** [comment]
Yep! The only two problems I have are:
- To use it inline, you have to use `../apkcrawler/apkcrawler.py` since you shouldn't clone this repo into the main one as it would try to upload. This means however that the files get downloaded in the main repo and you have to clean it up... Maybe set the downloaded files to always download in the location of the script?
- Also, I tried running the command with no prams to download all to test. I ended up force stopping it two minutes since I didn't know what was happening. We need some progress echoed.

**Comment by NicholasBuse** [comment]
1. I was hoping that it would become a submodule, thus I have it soft linked in the OpenGApps root right now...
2. There is file logging (apkcrawler.py.log) in the pwd

Now you can beat me to committing new APKs like Hangouts!

**Comment by bgiesing** [comment]
@NicholasBuse How did you link it? I tried linking to the directory and directly to the script but it still puts everything in the main repo dir.

**Comment by NicholasBuse** [comment]
I am on Cygwin , not linux, but  I used window's junction.exe from within the opengapps folder:

``
junction C:\git\apkcrawler apkcrawler
```

it does show an untracked folder (apkcrawler) in the root for git status, but I don't have write access to the repo, so I just git stash as needed...

**Comment by bgiesing** [comment]
@NicholasBuse I figured it out. LOL I was using relative file paths... (apkcrawler instead of ~/apkcrawler).

I am using Windows also. Trust me when I say, use VirtualBox with a Linux VM. It will be millions times easier and faster. Use the [Ubuntu `mini.iso`](http://cdimage.ubuntu.com/netboot/) to create it. When installing, just select basic server install and SSH then when you run the machine later and set up the vm ports to forward from 22 to 3022, all you do is run it Headless (open VB > Select VM > Click Headless Start under the Start dropdown) and SSH into the VM using WinSCP and Putty and Port 3022.

Sounds complicated, but once you set it up... It's fast (since the machine GUI isn't shown) and you can even SSH into it from another location. Plus, it is full Linux which means Cygwin issues with not having the correct utilities would be non-existent.

**Comment by NicholasBuse** [comment]
Just about completed with your virtual box suggestion.  I think it would be easier for me to have the local repo on my Windows C: drive instead of on some (HUGE) virtual disk. I'm not seeing the shared folder option mount point in my VM though...thoughts?

**Comment by bgiesing** [comment]
@NicholasBuse I actually don't use shared mount points. That is why the SSH is their with WinSCP, I just drag the file into the VM. If you do want to use it, you need to install the Guest Additions.

As for the VM being huge, if you ever need to recover space from the VM for the C drive:

- Install zerofree `sudo apt-get install zerofree`
- Reboot VM (normal boot) while holding Shift
- Select Recovery mode
- Run Zerofree `sudo zerofree /dev/sdaX` (X is your root partition)
- Shutdown VM completely
- Open Admin Windows CMD Prompt
- Run this `VBoxManage modifyvdi /path/to/the/image.vdi compact`

**Comment by NicholasBuse** [comment]
Sorry to be a pain, I only know linux enough to be dangerous...

I used the Ubuntu 14.04.3 LTS (x64) version, but i'm struggling with getting the android sdk (aapt, etc.) dependencies that most of our scripts depend on.  
- Did you download the zip from Android Developers?
- What Java JDK did you install?
- Is there an apt-get install package that I should use?

Thanks!
--Nick

**Comment by bgiesing** [comment]
Use google-android-build-tools-installer and default-jdk

On Wed, Aug 12, 2015, 7:34 PM Nicholas Buse <notifications@github.com>
wrote:

> Sorry to be a pain, I only know linux enough to be dangerous...
>
> I used the Ubuntu 14.04.3 LTS (x64) version, but i'm struggling with
> getting the android sdk (aapt, etc.) dependencies that most of our scripts
> depend on.
>
>    - Did you download the zip from Android Developers?
>    - What Java JDK did you install?
>    - Is there an apt-get install package that I should use?
>
> Thanks!
> --Nick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/apkcrawler/pull/1#issuecomment-130490536>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljk1PwzAQRH9NcqOy116v95BD2hQkigAhwd0fazdqq5bQCvj3RGEOozk8jV7unAsJ2rHb9LvbmQ7vX9yYQT3Ld__zWaeNLZe70JOol-GR4pu7H9e7Q319mKHtx9NQG6tOYTyu6tLpfGr3nQkWRDwJxYI5W-05muwhMxkGNO3UTXI5_jawVoo8caAkqCC7YnRR8yxIEHzkiJSQNSI5spRBGFJR_9Faiwlea4agHSdRWCR4wllpuV_V8bq_xUXq2jXQ_wF1Y0SA>

**Pull request merged**
